### ISSUE TITLE
All sensors becoming unavailable 

### ISSUE THREAD

**Issue by BNWEIN** [msp1974/homeassistant-jlrincontrol#135]
Having an issue last few days where all entities and sensors are becoming unavailable. I reload the integration and they all come back. I have tried both the latest stable and beta versions but both have the same issue 

This is in the logs 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 269, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/coordinator.py", line 521, in async_update_data
    await self.async_get_user_info()
  File "/config/custom_components/jlrincontrol/coordinator.py", line 265, in async_get_user_info
    user = await self.hass.async_add_executor_job(self.connection._login_user, self.connection.head)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jlrpy.py", line 188, in _login_user
    self.user_id = user_data['userId']
                   ~~~~~~~~~^^^^^^^^^^
KeyError: 'userId'

**Comment by ismarslomic** [comment]
What version are you currently running? Have you upgraded to `v2.2.6`?

**Comment by BNWEIN** [comment]
Currently on 3.0 Beta5 

Was having the same issue on 2.2.6

**Comment by BNWEIN** [comment]
Just went back to 2.2.6 now I’m getting an even stranger error about a “migration error”

Logger: homeassistant.config_entries
Source: config_entries.py:693
First occurred: 21:36:03 (1 occurrences)
Last logged: 21:36:03

Migration handler not found for entry my@email.com for jlrincontrol

**Comment by msp1974** [comment]
Once you have upgraded to the v3 beta you.cannot go back to v2.2.x without removing and readding.

I think this maybe a bug that did not get fixed correctly.in v2.2.6.  This api call to get user info has changed and I fixed it in 1 place but maybe not the other.  There is an open PR on jlrpy to fix but I implemented a workaround (not very well obviously!)

Can sort this tomorrow in v2.2.7 version.

**Comment by BNWEIN** [comment]
Thanks Mark. Seeing as I can’t go back, any chance you can implement a fix in a beta 3.01 version too?

really appreciate it

**Comment by msp1974** [comment]
Sorry yes meant to say that.  Will do both the release and beta

**Comment by msp1974** [comment]
Just been looking at this and the integration is correct but for some reason you do not get a correct response.  This maybe due to a change in the JLR api or something else.

I'm afraid I haven't got time to look at this for a few weeks and if it is also happening on v2.2.6 then this is something unusual.

Only things I can suggest now is to remove and install v2.2.6 and double check there is no space after your email address when adding back in (can happen if auto populated on phone).  Apart from the initial load, v2.2.6 does not use this Endpoint, so less likely to fail.

Where in the world are you?

**Comment by msp1974** [comment]
Sorry @BNWEIN - i was seeing this too so suspect it is a more widespread issue.  I have quickly made a beta6 that will only query the userinfo at the start and not again (as long as it gets units of measure).  Hopefully this will resolve.

The issue seems to be an inconsistant response from this endpoint, which not had time to look into as to why it is missing data sometimes when queried.

Let me know how you get on.

**Comment by BNWEIN** [comment]
Thanks Mark! 

Can I upgrade from beta 3 to Beta 6?

**Comment by msp1974** [comment]
Yes.

**Comment by rozza-m** [comment]
Jlr have locked out a load of 3rd party stuff. Eg octopus go no longer works. This might be the end. 😢

**Comment by msp1974** [comment]
> Jlr have locked out a load of 3rd party stuff. Eg octopus go no longer works. This might be the end. 😢

It's not the end...not yet anyway.  This has been circumvented for now and v2.2.6 and v3.0.0beta5 are the versions that overcame this.  However, there is also a few other api changes that JLR have made and that has caused this issue.

**Comment by ismarslomic** [comment]
@BNWEIN can we close this issue now?

**Comment by BNWEIN** [comment]
Yes seems resolved in Beta 6. Thank you all!
