### ISSUE TITLE
Climate device to set target temp for preconditioning

### ISSUE THREAD

**Issue by msp1974** [msp1974/homeassistant-jlrincontrol#38]
Can a climate device be used to manage the engine start/precondition temp setting and call service to start process as suggested by @zachamato

**Comment by zachamato** [comment]
I have a working switch to turn on/off remote start and will monitor remote start status. Might be easily ported to a climate device but so far I’m liking the easy “Alexa, start my car”  command. I also added to HomeKit with no issues.

The switch uses the last set RCC target value for now, but I’m sure that could be easily added.

I can create a pull request for you to review, I’m a bit of a novice but I based my device off lock.py and other integrations from Home Assistant.

**Comment by msp1974** [comment]
Sure, send a PR and let me have a look at it

**Comment by zachamato** [comment]
Think I did that right, but I submitted the PR. This is only for Remote Start (not EV) but maybe someone else can add those features. The switch should only work if the 'REON' service is enabled for the vehicle.

Also might be useful to update the switch status to on/off once the service call is successful rather than wait for the vehicle to periodically update.

**Comment by stefferber** [comment]
Looking for the same feature. Is @zachamato fork implementing a [`climate` ](https://www.home-assistant.io/integrations/climate/) service?
Would be great because then the [Thermostat Card ](https://www.home-assistant.io/lovelace/thermostat/) works right out of the box.

**Comment by ismarslomic** [comment]
@zachamato as I understood you have solved turning on/off precondition by use of a switch, correct? Could you maybe share the code?

I think also that having a climate entity would make a nicer user interface with usage of the Thermostat Card. However, this is kind of a hack. Just a example, a climate entity has a current and target temperature, and you can anytime change the target temperature. This behaviour would not fit exactly for precondition, since you can't change the target temperature after precondition has started (without restarting the precondition). And how would you visualise the remaining duration, that would need to be another sensor, since the Thermostat Card has no display of this information. We neither have the current temperature. To provide a user friendly experience, we need to add so many exceptions to the climate entity, that it will become too complex to maintain.

So I think maybe that we could either provide a switch for turning on/off precondition as part of the integration, or at least include a recipe on how to achieve this.

What is your thoughts?

**Comment by ismarslomic** [comment]
Closing stale issue
